### ISSUE TITLE
Add Molly to Encrypted Realtime Messaging recommendations

### ISSUE THREAD

**Issue by iAnonymous3000** [tnonate/thenewoil#29]
I'd like to suggest adding [Molly](https://molly.im) to the Encrypted Realtime Messaging section of the guide as a privacy-enhanced alternative for Android users.

### Suggested Entry (feel free to change the draft as you wish):
```
Molly

Pros:
- Security audited
- Hardened fork of Signal with enhanced security features
- Removes Google dependencies present in standard Signal
- RAM shredding for secure data removal
- Strict privacy-focused default settings
- Tor support via SOCKS proxy
- No Google Play Services required
- More reliable notifications on GrapheneOS compared to Signal

Cons:
- Android-only (limited to Android-based operating systems)
```

### Why Add Molly?
Molly serves a specific but important niche in the privacy-focused messaging ecosystem:
1. Provides a hardened, Google-free Signal experience for privacy-conscious Android users
2. Particularly valuable for GrapheneOS users who experience notification issues with standard Signal
3. Offers additional security features not present in standard Signal
4. Maintains Signal protocol compatibility while enhancing privacy

**Comment by tnonate** [comment]
I like Molly as much as the next guy - I'm actually currently using it on my Lineage phone and finding it MUCH more reliable than base Signal for timely notifications - but unfortunately I don't think it's a good recommendation for the site for many of the same reasons you've listed.

> Android-only

Our [criteria](https://thenewoil.org/en/criteria/#universal-requirements) explicitly requires recommendations to be multi-platform.

> More reliable notifications on GrapheneOS compared to Signal
> Provides a hardened, Google-free Signal experience for privacy-conscious Android users
> Particularly valuable for GrapheneOS users who experience notification issues with standard Signal

GrapheneOS falls outside the scope of the website. See the second-to-last paragraph on [this page](https://thenewoil.org/en/guides/moderately-important/mobile-habits/).

> Provides a hardened, Google-free Signal experience for privacy-conscious Android users
> Removes Google dependencies present in standard Signal
> Tor support via SOCKS proxy
> No Google Play Services required

All these are more advanced concerns that fall outside the scope of the site (though to be honest, I would LOVE to see more services become less dependent on Apple & Google, particularly in regards to push notifications, to the point where it becomes worth listing as a pro/con).

> Hardened fork of Signal with enhanced security features

I'm actually very uncomfortable when dealing with protocols (ie Matrix, KeePass) because I worry about confusing my target audience. This itself quickly becomes a miniature pro/con chart of its own where users now have to decide which client is best for them. The goal is to give users enough information to make the right choice for them without overwhelming them with decision fatigue. Most people are used to mainstream, locked-in apps where it just goes "download the app and start using it" as opposed to services like Matrix or Mastodon where it goes "you have a dozen different apps and ten times as many servers." It's incredibly overwhelming for a newbie and I aim to eliminate that as much as I can.

Let me know if you feel I'm wrong on this front. Like I said, I like Molly and have no issues with people using it, but I just don't think it's right for TNO.

**Comment by iAnonymous3000** [comment]
Thank you for the detailed response! I noticed Briar is currently listed in the Honorable Mentions section despite being Android-only. Could Molly fit there as well?

This keeps things simple and focused on solving a common user problem (notification reliability). Like Briar, it would give users another option when they need it, without complicating the main recommendations.

**Comment by tnonate** [comment]
I forgot all about Briar being listed there.

Yeah actually, I think Molly could fit very well as an honorable mention. Thanks for pointing that out!

**Comment by iAnonymous3000** [comment]
Perhaps, this format could help?

```
Molly is only available on Android and is a hardened version of Signal. If you're an Android user experiencing notification reliability issues with Signal, Molly might be a better choice while maintaining the same security and privacy benefits. It doesn't require Google services to function reliably.
```

Feel free to improvise accordingly.

**Comment by tnonate** [comment]
Added per latest commit: https://github.com/tnonate/thenewoil/commit/40714829dc173fa676091d08355e3842931d169d
